### ISSUE TITLE
Feature request: Add metadata to transport stream

### ISSUE THREAD

**Issue by sengsational** [sengsational/cwhelper#21]
@TPeterson94070 I need some help with the mapping between the fields in `CW_EPG_RECORDS` and the fields that are used in garybuhrmaster's implementation.

Please see the comments in https://github.com/sengsational/cwhelper/commit/28b85225f485f912ceec00dc7f299457af852e34

**Comment by TPeterson94070** [comment]
I just emailed my suggestions, repeated here:
Gtb   name | Cw_record.mdb   field
'Category' | SHOWTYPE
'ChannelAffiliate' | n/a
'ChannelImageURL' | n/a
'ChannelName' | CHANNEL   (should use PSIP name, but it’s not in History)
'ChannelNumber' | VIR+’.’+SUB
'EndTime' | ORIG_END
'EpisodeNumber' | n/a   (actually is in SUBTITLE, but…)
'EpisodeTitle' | SUBTITLE
'FirstAiring' | NEW
'ImageURL' | n/a
'OriginalAirdate' | AIRDATE
'ProgramID' | EPISODE
'RecordEndTime' | ENDTIME
'RecordStartTime' | STARTTIME
'RecordSuccess' | CONFIRMED
'Resume' | n/a
'SeriesID' | n/a   (not sure what this is supposed to be)
'StartTime' | ORG_START
'Synopsis' | DESCRIPTION
'Title' | TITLE

**Comment by sengsational** [comment]
Except for "NEW", I found all of the fields in my CW_EPG_RECORDS table.

**Comment by TPeterson94070** [comment]
Oops.  Sorry "NEW" is in the EPG dataset and not supplied in History.  I guess we can just skip it.

**Comment by TPeterson94070** [comment]
On further thought, I realized that CWHelper needs to skip 'RecordSuccess' also, because CONFIRMED only gets set "True" when CW_EPG runs after the capture has been done so it will always be "False" when CWHelper is writing the file.
