### ISSUE TITLE
Metadata not copied if file name contains ampersand

### ISSUE THREAD

**Issue by sengsational** [sengsational/cwhelper#26]
The database has %26 for ampersands so direct query `where filename = 'Something & Something'` does not find the record.

**Comment by TPeterson94070** [comment]
For the use case you mention, only the %26 would apply since CWHelper is already translating the %20 back to <space> and %2A would never occur.

**Comment by TPeterson94070** [comment]
BTW, this is done to prevent an issue with CWHelper's parsing of the /save command.  Ampersands are perfectly OK in filenames, so the %26 could be decoded prior to executing the /save command.

**Comment by sengsational** [comment]
I version of CW_EPG 5.4.149 and later, file names will contain "&" as opposed to "%26", so no change is required in CwHelper.

**Comment by TPeterson94070** [comment]
Funny that this was Issue #26. 😉  And funny that CWHelper was doing the right thing all along and CW_EPG was just putting a bogus filename in its History.

**Comment by sengsational** [comment]
I noticed to swirly confluence of "26" too (cue twilight zone music).
