### ISSUE TITLE
SeriesID metadata not inclulded if database lacks SUBTITLE entry

### ISSUE THREAD

**Issue by sengsational** [sengsational/cwhelper#31]
`SeriesID` JSON is populated from database field `SUBTITLE`, but if that does not exist, `SeriesID` does not get populated in the metadata.

I proposed this metadata should be generated as "C00" appended to a hash of the TITLE field.

**Comment by TPeterson94070** [comment]
It should be `C00EN` prefixed on the hash of the  `TITLE` field.

**Comment by sengsational** [comment]
There's a bit more processing now.  When it gets to work on `Title`, if the `SeriesID` isn't populated, it puts in the default plus hash of the TITLE db field.  I didn't test it, so I HOPE it will do that.

https://github.com/sengsational/cwhelper/commit/2904b79765e751618b4e17da5b7c0fb3a1fc3a46

**Comment by TPeterson94070** [comment]
Success.  Congrats!!
![image](https://github.com/sengsational/cwhelper/assets/29694051/3b2ad088-9b62-4112-a2fd-e2618cf12f6a)
