### ISSUE TITLE
Slot equals bug

### ISSUE THREAD

**Issue by sengsational** [sengsational/cwhelper#7]
The slot equals is broken.

This line isn't really even required, but if it's there, it needs to be checking to make sure both variables are NOT null:
https://github.com/sengsational/cwhelper/blob/06401820156d6424c24319f322e957dd3d3a3828/CwHelperC/src/org/cwepg/hr/Slot.java#L302

So should read "            if (end != null && other.end != null){"

And then this line, the comparison is wrong.  It should be "greater than" (if the time is greater than a minute, then it's not equal):
https://github.com/sengsational/cwhelper/blob/06401820156d6424c24319f322e957dd3d3a3828/CwHelperC/src/org/cwepg/hr/Slot.java#L306

So should read "                if (differenceMs > 60000){"

And likewise, the same two changes need to be made here:
https://github.com/sengsational/cwhelper/blob/06401820156d6424c24319f322e957dd3d3a3828/CwHelperC/src/org/cwepg/hr/Slot.java#L319

and here:
https://github.com/sengsational/cwhelper/blob/06401820156d6424c24319f322e957dd3d3a3828/CwHelperC/src/org/cwepg/hr/Slot.java#L323

**Comment by TPeterson94070** [comment]
Understood.  I'll make these edits and test.

**Comment by TPeterson94070** [comment]
They worked!

**Comment by sengsational** [comment]
I made if off the sandbar.  Good news that you've got these changes in.  Thanks for getting those things in and testing them.  If you push them and do a pull request, I'll merge to the feature branch.  Then, if we're satisfied this feature is done, I'll merge to the master branch.

**Comment by TPeterson94070** [comment]
I've done the pr. Those updates are included, but I'm confused about some of the earlier ones that I thought had been incorporated before. I assume that any repeats will be effectively ignored. 


-------- Original Message --------

**Comment by sengsational** [comment]
Resolved.  It was broken on 10/26/2010 in an attempt to make small differences in end-event timestamps irrelevant.  It was only broken for 13 years.  I suspect I was testing "dump compare" to see if it was working, and neglected to reverse the changes.  The lesson here is to put a "TODO" marker in the code, so these kinds of things won't get left in the code.
![Broken2010](https://github.com/sengsational/cwhelper/assets/15800701/d2b3538d-afb7-49ea-86c5-1338afc94181)

**Comment by sengsational** [comment]
Resolved.
